name: Release to maven central snapshots

on:
  push:
    branches:
      - 'main'
      - 'feature/release-library-sonar'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release-snapshot:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Gradle Properties
        run: |
            mkdir -p ~/.gradle
            touch ~/.gradle/gradle.properties
          
            echo "${{ secrets.GPG_SIGNING_KEY_BASE64 }}" | base64 --decode > ~/.gradle/secring.gpg
          
            echo "mavenCentralUsername=${{ secrets.SONATYPE_USERNAME }}" >> ~/.gradle/gradle.properties
            echo "mavenCentralPassword=${{ secrets.SONATYPE_PASSWORD }}" >> ~/.gradle/gradle.properties
            echo "signing.keyId=${{ secrets.GPG_SIGNING_KEY_ID }}" >> ~/.gradle/gradle.properties
            echo "signing.password=${{ secrets.GPG_SIGNING_PASSWORD }}" >> ~/.gradle/gradle.properties
            echo "signing.secretKeyRingFile=${user.home}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
        shell: bash

      - name: Publish to Sonatype Snapshot
        run: ./gradlew publishToMavenCentral --no-configuration-cache