name: Release to maven central staging

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Gradle Properties
        run: |
          mkdir -p ~/.gradle
          touch ~/.gradle/gradle.properties
          
          echo "${{ secrets.GPG_SIGNING_KEY_BASE64 }}" | base64 --decode > ~/.gradle/secring.gpg
          
          echo "mavenCentralUsername=${{ secrets.SONATYPE_USER }}" >> ~/.gradle/gradle.properties
          echo "mavenCentralPassword=${{ secrets.SONATYPE_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "signing.keyId=${{ secrets.GPG_SIGNING_KEY_ID }}" >> ~/.gradle/gradle.properties
          echo "signing.password=${{ secrets.GPG_SIGNING_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=~/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
        shell: bash

      - name: Publish to Sonatype Staging
        run: ./gradlew publishToMavenCentral --no-configuration-cache

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true