name: Release to maven central snapshots

on:
  push:
    branches:
      - 'main'
      - 'bugfix/workflows'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release-snapshot:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check for Changes in `lib/`
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- lib/; then
            echo "No changes in lib, skipping publish."
            echo "SKIP_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "Changes detected in lib, proceeding with publish."
            echo "SKIP_PUBLISH=false" >> $GITHUB_ENV
          fi

      - name: Checkout
        if: env.SKIP_PUBLISH == 'false'
        uses: actions/checkout@v4

      - name: Configure Gradle Properties
        if: env.SKIP_PUBLISH == 'false'
        run: |
            mkdir -p ~/.gradle
            touch ~/.gradle/gradle.properties
          
            echo "${{ secrets.GPG_SIGNING_KEY_BASE64 }}" | base64 --decode > ~/.gradle/secring.gpg
          
            echo "mavenCentralUsername=${{ secrets.SONATYPE_USER }}" >> ~/.gradle/gradle.properties
            echo "mavenCentralPassword=${{ secrets.SONATYPE_PASSWORD }}" >> ~/.gradle/gradle.properties
            echo "signing.keyId=${{ secrets.GPG_SIGNING_KEY_ID }}" >> ~/.gradle/gradle.properties
            echo "signing.password=${{ secrets.GPG_SIGNING_PASSWORD }}" >> ~/.gradle/gradle.properties
            echo "signing.secretKeyRingFile=$HOME/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
        shell: bash

      - name: Publish to Sonatype Snapshot
        if: env.SKIP_PUBLISH == 'false'
        run: ./gradlew publishToMavenCentral --no-configuration-cache